import React from 'react';

interface PrintFooterProps {
  printedBy?: string;
  signatureRequired?: boolean;
}

export function PrintFooter({ printedBy = 'System Admin', signatureRequired = false }: PrintFooterProps) {
  const currentDate = new Date().toLocaleString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });

  return (
    <div className="mt-8 pt-4 border-t border-slate-300 text-xs">
      {signatureRequired && (
        <div className="grid grid-cols-3 gap-8 mb-8 pt-12 text-center text-slate-700 font-semibold">
          <div className="border-t border-slate-400 pt-1">
            Customer / Borrower Signature
          </div>
          <div className="border-t border-slate-400 pt-1">
            Verified By Officer
          </div>
          <div className="border-t border-slate-400 pt-1">
            Authorized Signatory & Seal
          </div>
        </div>
      )}

      <div className="flex items-center justify-between text-[10px] text-slate-500 font-mono">
        <div>
          Generated By: <span className="font-bold">{printedBy}</span> | Date & Time: {currentDate}
        </div>
        <div>
          Computer Generated Official Document | ABS Finance Management Software
        </div>
      </div>
    </div>
  );
}
